Oldsu.Web/Pages/BaseLayout.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Types;
using Oldsu.Web.Authentication;
using Oldsu.Web.Utils;

namespace Oldsu.Web.Pages
{
    public class BaseLayout : PageModel
    {
        public UserInfo? AuthenticatedUserInfo { get; private set; }

        public BaseLayout(AuthenticationService authenticationService)
        {
            AuthenticatedUserInfo = authenticationService.AuthenticatedUserInfo;
        } 
        
        public static readonly (string PageName, string Link)[] PageMenuItems = new[]
        {
            (PageName: "Home", Link:  PathCorrection.Correct("/")),
            (PageName: "Beatmaps", Link: PathCorrection.Correct("/beatmaps")),
            (PageName: "Rankings", Link: PathCorrection.Correct("/leaderboard")),
        };
    }
}

Oldsu.Web/Pages/BeatmapListing.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Oldsu.Logging;
using Oldsu.Types;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages {
    public class BeatmapListing : BaseLayout {
        public Beatmapset[]? BeatmapSets { get; private set; }

        [FromQuery(Name = "query")] public string? SearchQuery { get; set; } = string.Empty;
        
        public async Task<IActionResult> OnGet() {
            await using Database database = new();

            var query = database.Beatmapsets.Where(b => b.OriginalBeatmapsetID == null);

            if(!string.IsNullOrEmpty(SearchQuery)) {
                this.BeatmapSets = await query.Where(s => s.Title.Contains(SearchQuery) || s.Artist.Contains(SearchQuery)).ToArrayAsync();
            }
            else {
                this.BeatmapSets = await query.ToArrayAsync();
            }
            
            return this.Page();
        }

        private LoggingManager _loggingManager;
        
        public BeatmapListing(AuthenticationService authenticationService, LoggingManager loggingManager) 
            : base(authenticationService)
        {
            _loggingManager = loggingManager;
        }
    }
}

Oldsu.Web/Pages/ChangeEmail.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Oldsu.Types;
using Oldsu.Utils;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages;

public class ChangeEmail : BaseLayout
{
    public string? ChangeEmailResult { get; set; }
    
    public async Task<IActionResult> OnGet()
    {
        string tokenIdentifier = Request.Query["token"];
        if (tokenIdentifier == null)
            return BadRequest();

        await using var database =  new Database();
 
        EmailChangeToken? token = await database.EmailChangeTokens.FindAsync(tokenIdentifier);

        if (token == null)
            return Unauthorized();

        database.EmailChangeTokens.Remove(token);
        await database.SaveChangesAsync();

        UserInfo userInfo = await database.UserInfo.FindAsync(token.UserID);

        if (await database.UserInfo.AnyAsync(u => u.Email == token.Email))
        {
            ChangeEmailResult = "That email is already in use.";

            return Page();
        }
        
        await using var transaction = await database.Database.BeginTransactionAsync();

        try
        {
            userInfo.Email = token.Email;

            await transaction.CommitAsync();
        }
        catch
        {
            ChangeEmailResult = "An error occurred when contacting the database.";
            await transaction.RollbackAsync();

            return Page();
        }

        ChangeEmailResult = "Email changed successfully.";
        
        return Page();
    }

    public ChangeEmail(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/ChangeEmailRequest.cshtml.cs
using System;
using System.Net.Mail;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Types;
using Oldsu.Utils;
using Oldsu.Web.Authentication;
using Oldsu.Web.Models;
using Oldsu.Web.Utils;

namespace Oldsu.Web.Pages;

public class ChangeEmailRequest : BaseLayout
{
    public string? ChangeEmailRequestError { get; set; }

    public IActionResult OnGet() => BadRequest();
    
    public async Task<IActionResult> OnPost([FromForm] ChangeEmailModel model)
    {        
        if (AuthenticatedUserInfo == null)
            return Unauthorized();

        if (!MailAddress.TryCreate(model.Email, out _))
        {
            ChangeEmailRequestError = "Invalid email provided.";
            return Page();
        }

        string token = TokenGenerator.GenerateToken(128);

        await using var database = new Database();
        await using var transaction = await database.Database.BeginTransactionAsync();

        try
        {
            database.EmailChangeTokens.Add(new EmailChangeToken
            {
                Token = token,
                Email = model.Email,
                UserID = AuthenticatedUserInfo.UserID
            });

            await database.SaveChangesAsync();
            await transaction.CommitAsync();
        }
        catch
        {
            ChangeEmailRequestError = "An error occurred when contacting the database.";
            await transaction.RollbackAsync();

            return Page();
        }

        await EmailSender.SendAsync(model.Email, "Email change request",
            $"Here the link you can follow to change your email: https://oldsu.ayyeve.dev/change_email?token={HttpUtility.UrlEncode(token)}\n" +
            $"If you did not expect this email, just ignore it.");

        return Page();
    }

    public ChangeEmailRequest(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/ChangePassword.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Oldsu.Types;
using Oldsu.Web.Authentication;
using Oldsu.Web.Models;

namespace Oldsu.Web.Pages;

public class ChangePassword : BaseLayout
{
    public string? Token { get; set; }
    public string? PasswordChangeResult { get; set; }
    
    public async Task<IActionResult> OnGet()
    {
        string token = Request.Query["token"];
        if (token == null)
            return BadRequest();

        await using var database =  new Database();

        if (!await database.PasswordChangeTokens.AnyAsync(b => b.Token == token))
            return Unauthorized();
        
        Token = token;
        
        return Page();
    }
    
    public async Task<IActionResult> OnPost([FromForm] ChangePasswordModel model)
    {
        await using var database =  new Database();
        
        if (model.Password.Length != 64)
        {
            PasswordChangeResult = "Password did not get hashed properly, are you using an old website?";
            return Page();
        }

        try
        {
            if (await database.ChangePasswordAsync(model.Token, model.Password))
                PasswordChangeResult = "Password changed successfully!";
            else
                PasswordChangeResult = "The password was not changed.";
        }
        catch
        {
            PasswordChangeResult = "An error occurred when updating the database.";
        }

        return Page();
    }

    public ChangePassword(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/ChangePasswordRequest.cshtml.cs
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Oldsu.Utils;
using Oldsu.Web.Authentication;
using Oldsu.Web.Utils;

namespace Oldsu.Web.Pages;

public class ChangePasswordRequest : BaseLayout
{
    public ChangePasswordRequest(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
    
    public async Task<IActionResult> OnPost()
    {
        if (AuthenticatedUserInfo == null)
            return Unauthorized();

        string token = TokenGenerator.GenerateToken(128);

        await using Database database = new Database();
        await database.RequirePasswordChange(AuthenticatedUserInfo.UserID, token);

        await EmailSender.SendAsync(AuthenticatedUserInfo.Email, "Oldsu - Change password",
            $"Here the link you can follow to change your password: https://oldsu.ayyeve.dev/change_password?token={HttpUtility.UrlEncode(token)}\n" +
            $"If you did not expect this email, CONTACT THE STAFF IMMEDIATELY.");

        return Page();
    }

    public IActionResult OnGet()
    {
        return Unauthorized();
    }

}

Oldsu.Web/Pages/Copyright.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages;

public class Copyright : BaseLayout
{
    public void OnGet()
    {
        
    }

    public Copyright(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/Dashboard.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages
{
    public class Dashboard : BaseLayout
    {
        public Types.UserPage UserPageInformation { get; set; }

        public async Task<IActionResult> OnGet()
        {
            if (AuthenticatedUserInfo == null)
                return Unauthorized();
            
            await using var db = new Database();
            UserPageInformation = await db.UserPages.FindAsync(AuthenticatedUserInfo.UserID) ?? new Types.UserPage();

            return Page();
        }

        public Dashboard(AuthenticationService authenticationService) : base(authenticationService)
        {
        }
    }
}

Oldsu.Web/Pages/DashboardUsers.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Oldsu.DatabaseServices.MySql;
using Oldsu.Enums;
using Oldsu.Logging;
using Oldsu.Types;
using Oldsu.Web.Authentication;
using Oldsu.Web.Models;

namespace Oldsu.Web.Pages;

public class DashboardUsers : PageModel
{
    public UserInfo AuthenticatedUserInfo { get; private set; }
    public string BanResult { get; set; } = "";
    public UserInfo AdminInformation { get; set; }
    public MySqlUserService UserService { get; set; }
    private LoggingManager _loggingManager;
    public string BanMessage { get; set; } = "";
    
    public DashboardUsers(AuthenticationService authenticationService, MySqlUserService userService,
        LoggingManager loggingManager)
    {
        AuthenticatedUserInfo = authenticationService.AuthenticatedUserInfo;
        UserService = userService;
        _loggingManager = loggingManager;
    }
    
    public async Task<IActionResult> OnGet()
    {
        if (AuthenticatedUserInfo != null 
            && (AuthenticatedUserInfo.Privileges == Privileges.Developer))
        {
            await using var db = new Database();
            AdminInformation = await db.UserInfo.FindAsync(AuthenticatedUserInfo.UserID) ?? new UserInfo();
            return Page();
        }
        
        return Forbid();
    }
    
    public async Task OnPostBanUsername([FromForm] BanSubmitModel banData)
    {
        if (AuthenticatedUserInfo != null
            && (AuthenticatedUserInfo.Privileges == Privileges.Developer))
        {
            await using var database = new Database();
            AdminInformation = await database.UserInfo.FindAsync(AuthenticatedUserInfo.UserID) ?? new UserInfo();
            banData.Admin = AdminInformation;
            var userInfo = database.UserInfo.Where(u => u.Username == banData.Username).FirstOrDefaultAsync().Result;
            if (userInfo != null) banData.UserID = (int) userInfo.UserID;
            if (banData.Username != null && banData.Reason != null)
            {
                try
                {
                    await UserService.SetUserBanByName(banData.Username, true, banData.Reason);
                    BanMessage =
                        $"User {banData.Username} is banned by {banData.Admin.Username}.\nReason: {banData.Reason}";
                    await _loggingManager.LogInfo<DashboardUsers>(BanMessage);
                }
                catch
                {
                    BanMessage = "Can't find user with this specific username";
                }
            }
            
        }
    }
    
    public async Task OnPostBanUserID([FromForm] BanSubmitModel banData)
    {
        if (AuthenticatedUserInfo != null
            && (AuthenticatedUserInfo.Privileges == Privileges.Developer))
        {
            await using var database = new Database();
            AdminInformation = await database.UserInfo.FindAsync(AuthenticatedUserInfo.UserID) ?? new UserInfo();
            banData.Admin = AdminInformation;
            var userInfo = database.UserInfo.Where(u => u.UserID == banData.UserID).FirstOrDefaultAsync().Result;
            if (userInfo != null) banData.Username = userInfo.Username;
            if (banData.Username != null && banData.Reason != null)
            {
                try
                {
                    await UserService.SetUserBanByID(banData.UserID, true, banData.Reason);
                    BanMessage = $"User {banData.Username} is banned by {banData.Admin.Username}.\nReason: {banData.Reason}";
                    await _loggingManager.LogInfo<DashboardUsers>(BanMessage);
                }
                catch
                {
                    BanMessage = "Can't find user with that id";
                }
            }
        }
    }
}

Oldsu.Web/Pages/ForgotPassword.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Oldsu.Types;
using Oldsu.Utils;
using Oldsu.Web.Authentication;
using Oldsu.Web.Models;
using Oldsu.Web.Utils;
using Org.BouncyCastle.Utilities.Collections;

namespace Oldsu.Web.Pages;

public class ForgotPassword : BaseLayout
{
    public bool Submitted { get; set; } = false;

    private async Task SendResetLink(string email)
    {
        try
        {
            await using var database = new Database();

            UserInfo? userInfo = await database.UserInfo.Where(u => u.Email == email).FirstOrDefaultAsync();
            
            if (userInfo == null)
                return;

            string token = TokenGenerator.GenerateToken(128);
            await database.RequirePasswordChange(userInfo.UserID, token);
            
            await EmailSender.SendAsync(userInfo.Email, "Oldsu - Change password",
                $"Here the link you can follow to change your password: https://oldsu.ayyeve.dev/change_password?token={HttpUtility.UrlEncode(token)}\n" +
                $"If you did not expect this email, CONTACT THE STAFF IMMEDIATELY.");
        }
        catch
        {
            // ignore
        }
    }
    
    public async Task<IActionResult> OnPost([FromForm] ForgetPasswordModel model)
    {
        await Task.WhenAll(Task.Delay(2000), SendResetLink(model.Email));
        Submitted = true;

        return Page();
    }

    public ForgotPassword(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/HomePage.cshtml.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Oldsu.Types;
using Oldsu.Web.Authentication;
using Oldsu.Web.Models;
using Oldsu.Web.Validators;

namespace Oldsu.Web.Pages
{
    [IgnoreAntiforgeryToken]
    public class HomePage : BaseLayout
    {
        public News? LatestNews { get; private set; }
    
        public async Task<IActionResult> OnGet()
        {
            await using var database = new Database();
            LatestNews = await database.News.OrderByDescending(n => n.Date).FirstOrDefaultAsync();
            
            return Page();
        }

        public HomePage(AuthenticationService authenticationService) : base(authenticationService)
        {
        }
    }
}

Oldsu.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages;

public class Privacy : BaseLayout
{
    public Privacy(AuthenticationService authenticationService) : base(authenticationService)
    {
    }
}

Oldsu.Web/Pages/Profile.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Oldsu.Web.Authentication;

namespace Oldsu.Web.Pages
{
    public class Profile : BaseLayout
    {
        public async Task<IActionResult> OnGet()
        {
            if (AuthenticatedUserInfo != null)
                return Redirect(PathCorrection.Correct($"/u/{AuthenticatedUserInfo.UserID}"));

            return Redirect(PathCorrection.Correct("/"));
        }

        public Profile(AuthenticationService authenticationService) : base(authenticationService)
        {
        }
    }
}

Oldsu.Web/Pages/BaseLayoutWithBanner.cshtml
@using Oldsu.Web

@{
    Layout = "BaseLayout";
}
<div class="banner_wrapper">
    <img src=@PathCorrection.Correct("/resources/image/banner.png") alt="oldsu! banner" class="banner_image">
</div>

@RenderBody()

Oldsu.Web/Pages/BeatmapListing.cshtml
@page "/beatmaps"
@using Oldsu.Types
@using Oldsu.Web
@model Oldsu.Web.Pages.BeatmapListing

@{
    Layout = "BaseLayoutWithBanner";
}


@* this might be retarded since this isn't a head *@
<link href=@PathCorrection.Correct("/resources/css/beatmap_listing.css") rel="stylesheet">
<link href=@PathCorrection.Correct("/resources/css/beatmap_preview.css") rel="stylesheet">

<div class="beatmap_listing_content" style="flex-direction: column">
    <form name="search_settings_wrapper">
        <div class="inputbar_wrapper" id="inputbar_beatmap_search">
            <p class="inputbar_label">Search for:</p>
            <input class="inputbar_text" type="text" name="query" value="@Model.SearchQuery"/>
        </div>
        <input type="submit" id="beatmap_search_submit" value="Search" class="submit_button">
    </form>
        
    <div class="beatmap_list">
        @{
            if(Model.BeatmapSets == null) {
                <p>No results match that query.</p>
            } else {
                foreach(Beatmapset beatmapSet in Model.BeatmapSets) {
                    <div class="beatmap_preview_wrapper" style="background-image: linear-gradient(#FFFFFF, #FFFFFF), url('/resources/image/discoprincebg.jpg');">
                        <p class="beatmap_preview_title">@beatmapSet.Title</p>
                        <p class="beatmap_preview_artist">@beatmapSet.Artist</p>    
                        <p class="beatmap_preview_mapper">Mapped by <a href="/u/@beatmapSet.CreatorID">@beatmapSet.CreatorName</a></p>
                        <p class="beatmap_preview_info" title="Ranked by @beatmapSet.RankedBy"><b>Ranked</b></p>
                    </div>
                }
            }
        }
    </div>
</div>

Oldsu.Web/Pages/ChangePasswordRequest.cshtml
@page "/dashboard/changePassword"
@model Oldsu.Web.Pages.ChangePasswordRequest

@{
    Layout = "BaseLayout";
}
<div class="register_content">

<div class="register_result">
    <span class="material-icons">error</span>
    <p>An email with the link to change the password has just been sent to your email address.</p>
</div>
</div>

Oldsu.Web/Pages/DashboardUsers.cshtml
@page "/admin/users"
@using Oldsu.Enums
@model Oldsu.Web.Pages.DashboardUsers
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
<nav class="navbar navbar-light bg-light p-3">
  <div class="d-flex col-12 col-md-3 col-lg-2 mb-2 mb-lg-0 flex-wrap flex-md-nowrap justify-content-between">
      <a class="navbar-brand" href="#">
          oldsu! admin
      </a>
      <button class="navbar-toggler d-md-none collapsed mb-3" type="button" data-toggle="collapse" data-target="#sidebar" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
  </div>
  <div class="col-12 col-md-4 col-lg-2">
      <input class="form-control form-control-dark" type="text" placeholder="Search" aria-label="Search">
  </div>
  <div class="col-12 col-md-5 col-lg-8 d-flex align-items-center justify-content-md-end mt-3 mt-md-0">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
        Hello, @Model.AdminInformation?.Username
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <li><a class="dropdown-item" href="#">Settings (No)</a></li>
        <li><a class="dropdown-item" href="#">Messages (No)</a></li>
        <li><a class="dropdown-item" href="#">Sign out (Fuck you)</a></li>
      </ul>
    </div>
  </div>
</nav>
  
  
<div class="container-fluid">
  <div class="row">
      <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-md-5">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/admindashboard-0" onclick="/admindashboard-0">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                <span class="ml-2">Dashboard</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/server" onclick="/admin/server">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                <span class="ml-2">Server Status</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/beatmaps" onclick="/admin/beatmaps">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                <span class="ml-2">Beatmaps</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/admin/users" onclick="/admin/users">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                <span class="ml-2">Users</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/reports" onclick="/admin/reports">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                <span class="ml-2">Reports</span>
              </a>
            </li>
          </ul>
        </div>
        </nav>
    <main class="col-md-9 ml-sm-auto col-lg-10 px-md-4 py-4">
      <div class="user-ban">
        <div class="card">
          <h2>Ban Users</h2>
          <div class="card">
            <h4>Using Username</h4>
            <form asp-page-handler="BanUsername" method="post" name="ban_form" class="form">
              <input type="text" class="form_username" id="username" maxlength="32" name="username" placeholder="Username" required> <br/>
              <input type="text" class="form_reason" id="reason" name="reason" placeholder="Ban reason" required> <br/>
              <p>Current admin: @Model.AdminInformation?.Username</p>
              <input type="submit" class="form_submit_button" id="ban_submit" name="ban_submit" value="YEET!">
            </form>
          </div>
          <br/>
          <div class="card">
            <h4>Using ID</h4>
            <form asp-page-handler="BanUserID" method="post" name="ban_form" class="form">
              <input type="number" class="form_userid" id="userid" maxlength="32" name="userid" placeholder="UserID" required> <br/>
              <input type="text" class="form_reason" id="reason" name="reason" placeholder="Ban reason" required> <br/>
              <p>Current admin: @Model.AdminInformation?.Username</p>
              <input type="submit" class="form_submit_button" id="ban_submit" name="ban_submit" value="YEET!">
            </form>
          </div>
          <h3 class="clearfix">@Model.BanMessage</h3>
        </div>
      </div>
    </main>
  </div>
</div>
</body>
</html>

<style>
      
.sidebar {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  z-index: 100;
  padding: 90px 0 0;
  box-shadow: inset -1px 0 0 rgba(0, 0, 0, .1);
  z-index: 99;
}


@@media (max-width: 767.98px) {
  .sidebar {
    top: 11.5rem;
    padding: 0;
  }
}

.navbar {
  box-shadow: inset 0 -1px 0 rgba(0, 0, 0, .1);
}


@@media (min-width: 767.98px) {
  .navbar {
    top: 0;
    position: sticky;
    z-index: 999;
  }
}


.sidebar .nav-link {
  color: #333;
}

.sidebar .nav-link.active {
  color: #0d6efd;
}

.card-body {
  font-size: 10px;
}
  
</style>